name: K Test
favicon: null
layout_spectrum: 0.3904084770474583
typography_spectrum: 0.8490368591155857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4256553999148309
  lightness: 0.028101133182644844
  saturation: 0.43340591597370803
  rhythmicContrast: 0.4417115426622331
purpose: []
